import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Grid,
  Chip,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  IconButton,
  Alert,
  CircularProgress,
  Fab,
  DialogContentText,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';
import {
  Public as CountryIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
} from '@mui/icons-material';
import { countryApi } from '../services/api';

const Countries = () => {
  const [countries, setCountries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);
  const [openDeleteDialog, setOpenDeleteDialog] = useState(false);
  const [editingCountry, setEditingCountry] = useState(null);
  const [deleteCountryId, setDeleteCountryId] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    is_active: true,
  });

  // Load countries on component mount
  useEffect(() => {
    fetchCountries();
  }, []);

  const fetchCountries = async () => {
    try {
      setLoading(true);
      setError(null);
      console.log('Fetching countries...');
      const response = await countryApi.getAll();
      console.log('Countries response:', response);
      
      let countriesList = [];
      if (Array.isArray(response)) {
        countriesList = response;
      } else if (response?.data && Array.isArray(response.data)) {
        countriesList = response.data;
      } else if (response?.results && Array.isArray(response.results)) {
        countriesList = response.results;
      }
      
      console.log('Processed countries list:', countriesList);
      setCountries(countriesList);
    } catch (error) {
      console.error('Error fetching countries:', error);
      setError('Failed to load countries. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenDialog = (country = null) => {
    setError(null); // Clear any previous errors
    if (country) {
      setEditingCountry(country);
      setFormData({
        name: country.name || '',
        is_active: country.is_active !== undefined ? country.is_active : true,
      });
    } else {
      setEditingCountry(null);
      setFormData({
        name: '',
        is_active: true,
      });
    }
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
    setEditingCountry(null);
    setFormData({
      name: '',
      is_active: true,
    });
  };

  const handleInputChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSubmit = async () => {
    try {
      // Validate required fields
      if (!formData.name || formData.name.trim() === '') {
        setError('Please fill in the country name.');
        return;
      }

      // Prepare data according to API specification
      const countryData = {
        name: formData.name.trim(),
        is_active: formData.is_active
      };
      
      console.log('Country data to send:', countryData);
      
      if (editingCountry) {
        // Update existing country - include country_id in request body for PATCH
        const updateData = {
          ...countryData,
          country_id: editingCountry.country_id || editingCountry.id
        };
        
        console.log('Updating country with data:', updateData);
        const response = await countryApi.update(updateData);
        console.log('Country update response:', response);
        
        setCountries(countries.map(country => 
          (country.country_id || country.id) === (editingCountry.country_id || editingCountry.id)
            ? { ...country, ...response.data || response }
            : country
        ));
      } else {
        // Create new country using PATCH method - let API auto-generate country_id
        const createData = {
          ...countryData
          // country_id will be auto-generated by API
        };
        
        console.log('Creating country with data:', createData);
        const response = await countryApi.create(createData);
        console.log('Country create response:', response);
        
        setCountries([...countries, response.data || response]);
      }
      handleCloseDialog();
    } catch (error) {
      console.error('Error saving country:', error);
      console.error('Error response:', error.response);
      console.error('Error response data:', error.response?.data);
      console.error('Error response status:', error.response?.status);
      
      const errorMessage = error.response?.data?.detail || 
                          error.response?.data?.message || 
                          error.response?.data?.error ||
                          error.message;
      
      setError(`Failed to ${editingCountry ? 'update' : 'create'} country: ${errorMessage}`);
    }
  };

  const handleDeleteClick = (countryId) => {
    setDeleteCountryId(countryId);
    setOpenDeleteDialog(true);
  };

  const handleDeleteConfirm = async () => {
    try {
      await countryApi.delete(deleteCountryId);
      setCountries(countries.filter(country => 
        (country.country_id || country.id) !== deleteCountryId
      ));
      setOpenDeleteDialog(false);
      setDeleteCountryId(null);
    } catch (error) {
      console.error('Error deleting country:', error);
      setError(`Failed to delete country: ${error.response?.data?.detail || error.message}`);
    }
  };

  const handleDeleteCancel = () => {
    setOpenDeleteDialog(false);
    setDeleteCountryId(null);
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '50vh' }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4">
          Countries Management
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => handleOpenDialog()}
        >
          Add Country
        </Button>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError(null)}>
          {error}
        </Alert>
      )}

      <Grid container spacing={3}>
        {countries.map((country) => (
          <Grid item xs={12} sm={6} md={4} key={country.country_id || country.id}>
            <Card sx={{ height: '100%' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <CountryIcon sx={{ mr: 2, color: 'primary.main' }} />
                  <Box sx={{ flexGrow: 1 }}>
                    <Typography variant="h6" component="div">
                      {country.name}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      ID: {country.country_id || country.id}
                    </Typography>
                  </Box>
                  <Chip
                    label={country.is_active ? 'Active' : 'Inactive'}
                    color={country.is_active ? 'success' : 'default'}
                    size="small"
                  />
                </Box>
                
                <Box sx={{ display: 'flex', gap: 1, mt: 2 }}>
                  <IconButton
                    size="small"
                    color="primary"
                    onClick={() => handleOpenDialog(country)}
                  >
                    <EditIcon />
                  </IconButton>
                  <IconButton
                    size="small"
                    color="error"
                    onClick={() => handleDeleteClick(country.country_id || country.id)}
                  >
                    <DeleteIcon />
                  </IconButton>
                </Box>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      {/* Add/Edit Country Dialog */}
      <Dialog open={openDialog} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <DialogTitle>
          {editingCountry ? 'Edit Country' : 'Add New Country'}
        </DialogTitle>
        <DialogContent>
          <Box sx={{ pt: 2 }}>
            <TextField
              fullWidth
              label="Country Name"
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              margin="normal"
              required
              helperText="Required field"
            />
            <FormControl fullWidth margin="normal">
              <InputLabel>Status</InputLabel>
              <Select
                value={formData.is_active}
                onChange={(e) => handleInputChange('is_active', e.target.value)}
                label="Status"
              >
                <MenuItem value={true}>Active</MenuItem>
                <MenuItem value={false}>Inactive</MenuItem>
              </Select>
            </FormControl>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Cancel</Button>
          <Button onClick={handleSubmit} variant="contained">
            {editingCountry ? 'Update' : 'Create'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={openDeleteDialog} onClose={handleDeleteCancel}>
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Are you sure you want to delete this country? This action cannot be undone.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleDeleteCancel}>Cancel</Button>
          <Button onClick={handleDeleteConfirm} color="error" variant="contained">
            Delete
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default Countries;
